### ISSUE TITLE
Initializer for conditional binding must have Optional type, not '[T]'

### ISSUE THREAD

**Issue by ajpinedam** [zendobk/RealmMapper#11]
When using Pod version 2.3.0 Xcode fail to build with error: 

> Initializer for conditional binding must have Optional type, not '[T]'

Error is in **Operator.swift** file, line 55 
`let objs = Mapper<T>().mapArray(JSONArray: json) else { return }`

Xcode 8.3.3
OS Mac Sierra
Deployment Target 9.1

**Podfile**

```
# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'RMTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmMapper', '~> 2.3'
  # Pods for RMTest
end
```

If you need more information let me know.

Thanks.-

**Comment by zendobk** [comment]
Thanks for your feedvack @ajpinedam. Currently, dependence `ObjectMapper` had a breaking change API from version `2.2.6` to `2.2.7`. So you can fix `ObjectMapper` version to `2.2.6` in your `Podfile`, `ReamMapper` will run well. I'll update later.
