### ISSUE TITLE
get "No calls to throwing functions occur within 'try' expression" in swift4 

### ISSUE THREAD

**Issue by icefox57** [zendobk/RealmMapper#13]
No calls to throwing functions occur within 'try' expression
![image](https://user-images.githubusercontent.com/1716737/31213104-4cda3a1a-a96a-11e7-932b-f17440a1eff2.png)

is there an elegant way to solve this ?
May i have to write do try catch?

**Comment by zendobk** [comment]
`<-` operator doesn't throw an exception. So you should remove `try`.
