### ISSUE TITLE
if realm file is encrypted , will throw RLMException

### ISSUE THREAD

**Issue by icefox57** [zendobk/RealmMapper#5]
I have encrypted realm file
when i get response and map json to realm object
i got RLMException "Realm at path '%s' already opened with different encryption key"

and i found at line 91 , 
let realm = try Realm()

will use realm without encryptionKey.

**Comment by zendobk** [comment]
@icefox57 Are you using multiple Realm? If not, could you try to change `Realm.Configuration.defaultConfiguration`?
```
Realm.Configuration.defaultConfiguration = {
    var config = Realm.Configuration.defaultConfiguration
    config.deleteRealmIfMigrationNeeded = true
    config.encryptionKey = "Abc123".data(using: .utf8)
    return config
}()
```
I'll update to support multiple Realm, but not today.
